postgres:
  restart: always
  image: postgres:alpine
  container_name: yet-another-postgres  
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/
  environment:
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: $POSTGRES_DB
    # DATABASE_HOST: $DATABASE_HOST
    # DATABASE_PORT: $DATABASE_PORT